#!/bin/bash

# VRF creation example.
# Virtual Routing and Forwarding (VRF) allows for the separation of
# routing tables, independently processing of network paths.

# Creation of VRFs in Linux is the creation of a network device,
# which will then serve as a master to the attached interfaces.

# For more information, consult the VRF documentation inside the 
# Linux Kernel in: https://www.kernel.org/doc/Documentation/networking/vrf.txt
# FRR configuration present in: 
# https://gist.github.com/rubensfig/ef4a8663ad0c13639ffc78ac2ec62f6c

# With the following physical topology:

# +--------+       +------------+
# | SERVER |       | CONTROLLER |
# +--------+       +------------+
#   eth1 (ns10) ------> port1
#   eth2 (ns10) ------> port2
#   eth3 (ns20) ------> port3
#   eth4 (ns30) ------> port4

# This script will create the following logical connections:

# port1 (VLAN10) ---+             +----- swbridge.10 +--> red
#                   |             |
# port2 (VLAN10) ---+             |
#                   |--> swbridge <----- swbridge.20 +--> blue
# port3 (VLAN20) ---+             |
#                   |             |
# port4 (VLAN30) ---+             +----- swbridge.30 +--> green

# IP addressing:
# swbridge.10 = 10.0.10.1/24
# swbridge.20 = 10.0.20.1/24
# swbridge.30 = 10.0.30.1/24

PORTA=${PORTA:-port1}
PORTB=${PORTB:-port2}
BRIDGE=${BRIDGE:-swbridge}

VRF=${VRF:-red}
VRF_LIST=($VRF)

VRF_TABLE_ID=${VRF_TABLE_ID:-254}
VRF_ID_LIST=($VRF_TABLE_ID)

BR_VLAN=${BR_VLAN:-10}
BR_VLAN_LIST=($BR_VLAN)
  
SVI_IP=${SVI_IP:-10.0.10.1/24}
SVI_IP_LIST=($SVI_IP)
NEI_IP=${NEI_IP:-10.0.100.2}

function setup() {
  ## vrf
ip link add ${VRF_LIST[$i]} type vrf table 254
ip link set ${VRF_LIST[$i]} up

  ## bridge
  ip link add name swbridge type bridge vlan_filtering 1 vlan_default_pvid 0
  ip link set swbridge up

  ## port 1
  ip link set port1 master swbridge
  bridge vlan add vid 254 dev port1
  ip link set port1 up

  ## port 2
  ip link set port2 master swbridge
  bridge vlan add vid 254 dev port2
  ip link set port2 up

  ## SVI
  ip link add link swbridge name swbridge.254 type vlan id 254
  bridge vlan add vid 254 dev swbridge self
  ip link set swbridge.254 up

  ### SVI - VRF enslavement
  ip link set swbridge.254 vrf red

  ## IP Address attribution
  ip add add 10.0.0.1/24 dev swbridge.254
}

function teardown() {
  for i in {1..${#VRF_LIST[@]}}; do
    ip link del ${VRF_LIST[$i]}
  done

  ip link del ${BRIDGE}
}
