---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD012: false # Allow multiple blank lines
MD013: false # Allow any line length
MD014: false # Allow Commands without output
MD022: false # Don't require blank lines around headings
MD024: false # Allow duplicate headings
MD025: false # Allow multiple h1 headings
MD029: false # Don't require ordered list item prefix to be ordered
MD030: false # Don't require spaces after list markers
MD031: false # Don't require blank lines around fences
MD032: false # Don't require blank lines around lists
MD033: false # Allow inline HTML
MD034: false # Allow bare URLs (misbehaves with templates)
MD040: false # Don't require language for fenced codeblocks
MD043: false # Don't enforce a heading structure
MD049: false # Don't require consistent emphasis style
