---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD013:
  code_blocks: false # allow code blocks to exceed 80 characters
  tables: false # allow tables to exceed 80 characters
MD024:
  siblings_only:  true # Require unique headings within one level
MD025: false # Allow multiple h1 headings
MD029: false # Don't require ordered list item prefix to be ordered
MD033:
  allowed_elements:
    - br
    - iframe
    - sup
MD034: false # Allow bare URLs (misbehaves with templates)
MD040: false # Don't require language for fenced codeblocks
MD043: false # Don't enforce a heading structure
MD049: false # Don't require consistent emphasis style
